import { z } from 'zod'

export const PostStoreWisePolicySchema = z.object({
  //"storeSpecificPolicyID": 0,
  storeID: z.string().optional(),
  fromDate: z.string().optional(),
  toDate: z.string().optional(),
  pendingSettlementDays: z.number().optional(),
  footfallEntryRequiredInDaySettlement: z.enum(['Y', 'N']).optional(),
  maxAllowDiscountPolicyValidationID: z.string().optional(),
  maxBillAmountSinglePOSBill: z.number().optional(),
  pan: z.string().optional(),
  creditCardDetailsCapturePolicyID: z.string().optional(),
  isCCardAuthNoEntryMandatory: z.enum(['Y', 'N']).optional(),
  allowBackDateEntry: z.enum(['Y', 'N']).optional(),
  backDateEntryDays: z.number().optional(),
  negativeStockCheckingModeID: z.string().optional(),
  allowItemLevelDiscount: z.enum(['Y', 'N']).optional(),
  maxAllowDiscountPercentage: z.number().optional(),
  allowBillLevelDiscount: z.enum(['Y', 'N']).optional(),
  maxAllowDiscountAmount: z.number().optional(),
  allowToSelectActivePromotionFromList: z.enum(['Y', 'N']).optional(),
  allowToClearAppliedPromotion: z.enum(['Y', 'N']).optional(),
  salePersonTaggingMandatory: z.enum(['Y', 'N']).optional(),
  salePersonTaggingPolicyID: z.string().optional(),
  customerTaggingMandatory: z.enum(['Y', 'N']).optional(),
  returnOfItemWithin: z.number().optional(),
  creditNoteValidityDays: z.number().optional(),
  billTaggingMandatoryDuringReturn: z.enum(['Y', 'N']).optional(),
  noOfCopiesToBePrint: z.number().optional(),
  excessGoodsReceiptTolerancePercentage: z.number().optional(),
  shortGoodsReceiptTolerancePercentage: z.number().optional(),
  allowReceiveDamagedGoods: z.enum(['Y', 'N']).optional(),
  dueDateMandatoryInPOSOrder: z.enum(['Y', 'N']).optional(),
  minPercentageOfAdvanceDuringPOSOrder: z.number().optional(),
  posOrderCancellationIsMandatory: z.enum(['Y', 'N']).optional(),
})
